name: advent2018
version: 0.1.0.0
synopsis: Advent of Code 2018 solutions in Haskell
github: cnr/advent2018

ghc-options: -Wall -O2

dependencies:
  - base
  - containers
  - megaparsec
  - mtl
  - split

library:
  source-dirs: lib
  exposed-modules:
    - Common

executables:

  day01:
    main: src/Day01.hs
    dependencies: [advent2018]

  day02:
    main: src/Day02.hs
    dependencies: [advent2018]

  day03:
    main: src/Day03.hs
    dependencies: [advent2018]

  day04:
    main: src/Day04.hs
    dependencies: [advent2018]

  day05:
    main: src/Day05.hs
    dependencies: [advent2018]

  day06:
    main: src/Day06.hs
    dependencies: [advent2018]

  day07:
    main: src/Day07.hs
    dependencies: [advent2018]

  day08:
    main: src/Day08.hs
    dependencies: [advent2018]

  day09:
    main: src/Day09.hs
    dependencies: [advent2018]
